#!/bin/sh


#4.1排序文本
#行的排序
#sort:将输入行按照键值字段与数据类型选项以及locale排序
#sort [option] [file]

#行的排序：LC_ALL=c sort file
#
#

#以字段排序:-k 指定排序字段 -t选择定界符
#
#sort -t: -k1,1 /etc/passwd
#可以含有多个-k选项，分别排序
#-u只显示键值的一条记录
#-t:指定字段定界符
#

#文本块排序
#cat my-text |
#awk -v RS="" '{gsub("\n","^z");print}' |
#sort -f |
#awk -v ORS="\n\n" '{gsub("^z","\n");print}' |
#grep -v '# sortkey'
#
#



#4.1.4 sort的效率
#
#
 
#4.1.5 sort的稳定性
#sort -t_ -k1,1 -k2.2 <<EOF
#
#结论：不稳定

#4.2 删除重复
#删除数据流里连续重复的记录
#参数：
#-c 在每个输出行之前加上该行重复的次数
#-d 仅显示重复的行
#-u 仅显示未重复的行
#uniq有时会拿来与diff工具搭配应用（比如说）


#4.3重新格式化段落
#
#sed -n -e 9991,10010p /usr/dict/words | fmt -w 30
#
#


#计算行数、字数以及字符数
#wc -c -w -l

#打印命令暂时跳过


#提取开头或结尾数行
#head 
#
#tail
#选项 -f 进入循环重复输出
#
 

#其他命令
#dd
#file
#od
#strings
#
#
